export const ActionTypes = {
    //getuser
    SET_USERS: "SET_USERS",
    SELECT_USER: "SELECT_USER",
    REMOVE_SELECT_USER: "REMOVE_SELECT_USER",
    //Auth user
    LOGIN_USER: "LOGIN_USER",
    REGISTER_USER: "REGISTER_USER",
    LOAD_USER: "LOAD_USER",
    LOGOUT_USER: "LOGOUT_USER",
    //Get tasks
    GET_ALL_TASKS: "GET_ALL_TASKS",
    SET_TASKS: "SET_TASKS",
    SELECT_TASK: "SELECT_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    UPDATE_TASK: "UPDATE_TASK"
}