export const ActionTypes = {
    SET_USERS: "SET_USERS",
    SELECT_USER: "SELECT_USER",
    REMOVE_SELECT_USER: "REMOVE_SELECT_USER",
    LOGIN_USER: "LOGIN_USER",
    REGISTER_USER: "REGISTER_USER",
    LOAD_USER: "LOAD_USER",
    LOGOUT_USER: "LOGOUT_USER"

}